[package]
name = "app_state"
version = "0.1.0"
authors = ["Chris Sampson <csampson@appliedsystems.com>"]
edition = "2018"

[dependencies]
moxie = "*"
mox = "*"
topo = "*"
illicit = "*"
legion = "0.3.1"
engine = { path = "../engine", version = "0.1.0"}
